const { jsPDF } = require("jspdf");
const autoTable = require("jspdf-autotable")
const { DateTime } = require("luxon");

const enCreatePDF = (personalData, allergyData, medicationData) => {
  const { firstName, lastName, email, phoneNumber, dateOfBirth, sex, streetNumber, city, state, postalCode, country } = personalData
  const formattedAllergy = allergyData.map(i => Object.values(i));
  const formattedMedication = medicationData.map(i => Object.values(i));

  let sexLocalized

  if (sex === "male") {
    sexLocalized = "Male"
  } else {
    sexLocalized = "Female"
  }

  const doc = new jsPDF();
  
  doc.autoTable({
    bodyStyles: { halign: "right" },
    body: [
      [DateTime.local().setLocale("en").toLocaleString("DATE_SHORT")],
    ],
    theme: "plain"
  })

  doc.autoTable({
    headStyles: { fontSize:16 },
    head: [
      ["Patient questionnaire"],
    ],
    theme: "plain"
  })

  doc.autoTable({
    head: [
      ["First name", "Last name", "Date of birth", "Biological sex"]
    ],
    body: [
      [firstName, lastName, DateTime.fromISO(dateOfBirth).setLocale("en").toLocaleString("DATE_SHORT"), sexLocalized],
    ],
    theme: "plain",
  })
  doc.autoTable({
    head: [
      ["Email", "Phone number"]
    ],
    body: [
      [email, phoneNumber],
    ],
    theme: "plain",
  })
  doc.autoTable({
    head: [
      ["Residential address"]
    ],
    body: [
      [`${streetNumber}, ${postalCode} ${city} ${state} ${country}`],
    ],
    theme: "plain",
  })

  doc.autoTable({
    head: [["Allergy", "Symptom"]],
    body: formattedAllergy
  })

  doc.autoTable({
    head: [["Medication", "Condition", "Frequency", "Dose"]],
    body: formattedMedication,
  })

  doc.setFontSize(10)
  doc.setFont("helvetica")
  doc.text("This patient questionnaire was generated by EHR", 14, doc.lastAutoTable.finalY + 10)

  const string = doc.output("arraybuffer");
  return string
}

module.exports = { enCreatePDF }