export const AUTHENTICATED_FAILED = "AUTHENTICATED_FAILED";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const USERLOADED_SUCCESS = "USERLOADED_SUCCESS";
export const USERLOADED_FAILED = "USERLOADED_FAILED";