export const AUTHENTICATED_FAILED = "AUTHENTICATED_FAILED";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const USERLOADED_SUCCESS = "USERLOADED_SUCCESS";
export const USERLOADED_FAILED = "USERLOADED_FAILED";
export const PATIENT_QUESTIONNAIRE_LOADED_SUCCESS = "PATIENT_QUESTIONNAIRE_LOADED_SUCCESS";
export const PATIENT_QUESTIONNAIRE_LOADED_FAILED = "PATIENT_QUESTIONNAIRE_LOADED_FAILED";